#!/bin/bash

# Number of docker containers running
count=$(docker ps -q | wc -l | sed -r 's/^0$//g')
# Recent docker container IP
# recent_ip=$(docker inspect dev-django -f "{{ .NetworkSettings.Networks.intempus.IPAddress }}" $(docker ps -ql))

echo "$LABEL$count"
# echo "$LABEL$count: $recent_ip"
